"""The Collect card (FR-2.1 through FR-2.11, FR-3.6, FR-3.7).

Mirrors ``mockup/widget-collect.html`` and ``widget-collect-filled.html``: a word
input, single-select part-of-speech chips, a collection dropdown with an inline
"+ New collection..." flow, an Auto/Manual meaning toggle, a lookup status line or
manual meaning/example fields depending on the toggle, and a Save button.

Three behaviours are worth stating because they are easy to get wrong:

* **Save is enabled the moment a word and a type exist**, regardless of lookup state.
  The whole point of FR-2.8 is that a slow dictionary cannot cost the user a capture.
* **Lookup completion arrives on a worker thread.** Touching widgets from there would
  be undefined behaviour in Qt, so the result is marshalled onto the UI thread via a
  signal before anything is rendered.
* **Switching to Manual cancels any in-flight lookup.** Otherwise a dictionary
  response could land after the user has already started typing their own
  definition and silently overwrite it (FR-2.11).
"""

from __future__ import annotations

from collections.abc import Callable
from enum import Enum, auto

from PySide6.QtCore import Qt, Signal
from PySide6.QtGui import QColor, QKeyEvent
from PySide6.QtWidgets import (
    QComboBox,
    QFrame,
    QGraphicsDropShadowEffect,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QVBoxLayout,
    QWidget,
)

from vocabulary_trainer.domain.models import (
    LookupResult,
    LookupSource,
    PartOfSpeech,
    WordEntry,
)
from vocabulary_trainer.domain.word_list import parse_word_list
from vocabulary_trainer.services.collect_service import (
    BatchOutcome,
    CollectService,
    LookupHandle,
    SaveStatus,
)
from vocabulary_trainer.services.errors import ValidationError
from vocabulary_trainer.ui.widget.anchoring import Rect, place_beside

__all__ = ["CARD_WIDTH", "CollectCardPopup", "describe_source"]

CHIP_LABELS = {
    PartOfSpeech.NOUN: "N",
    PartOfSpeech.VERB: "V",
    PartOfSpeech.ADJECTIVE: "adj",
    PartOfSpeech.ADVERB: "adv",
    PartOfSpeech.PHRASE: "ph",
}
"""Short labels for the type chips.

Display only -- what gets saved is still ``PartOfSpeech.value`` (the full word),
because the workbook is meant to be readable in Excel and the lookup pipeline
matches definitions on the real part-of-speech name.

The full words did not fit: five of them need more room than the 270px card, so Qt
compressed the chips and clipped their text mid-word ("noun" rendered as "1our",
"adjective" as "jecti"). Abbreviating is preferable to widening the card, which
has to stay narrow enough to sit beside the widget without covering what the user
is reading. Each chip carries the full word as its tooltip so the short form never
has to be guessed at.
"""

CARD_WIDTH = 270
"""Matches ``.collect-card`` in its resolved state."""

NEW_COLLECTION_SENTINEL = "__new__"
"""Dropdown value standing in for "+ New collection...", as in the mockup."""


class MeaningMode(Enum):
    """Whether this card looks up a definition or takes one typed by the user."""

    AUTO = auto()
    MANUAL = auto()


class EntryMode(Enum):
    """Whether this card captures one word or a comma-separated list (FR-2.12)."""

    SINGLE = auto()
    MULTIPLE = auto()


def describe_source(source: LookupSource) -> str:
    """Status-line text naming where a definition came from (FR-3.6).

    The mockups say "Cambridge Dictionary", which the product dropped before v2. That
    copy is stale and is deliberately not reproduced (NFR-UI-03).
    """
    return {
        LookupSource.OLLAMA: "Generated by local AI model",
        LookupSource.LOCAL_DICTIONARY: "Found in offline dictionary",
        LookupSource.FREE_DICTIONARY: "Found in Free Dictionary",
        LookupSource.MERRIAM_WEBSTER: "Found in Merriam-Webster",
        LookupSource.GOOGLE_TRANSLATE: "Translated to Vietnamese",
        LookupSource.NONE: "No definition found \u2014 saved with type only",
    }[source]


class CollectCardPopup(QWidget):
    """Minimal capture form anchored to the widget."""

    _lookup_finished = Signal(object)
    """Carries a :class:`LookupResult` from the worker thread onto the UI thread."""

    def __init__(
        self,
        collect_service: CollectService,
        on_duplicate: Callable[[WordEntry, WordEntry], None],
        on_closed: Callable[[], None] | None = None,
        on_lookup_reported: Callable[[str, LookupHandle], None] | None = None,
    ) -> None:
        super().__init__()
        self._service = collect_service
        self._on_duplicate = on_duplicate
        self._on_closed = on_closed
        self._on_lookup_reported = on_lookup_reported
        """Hands a saved word's in-flight lookup to whoever announces its outcome.

        Called with ``(word, handle)``. The Application owns the resulting speech
        bubble rather than this card, because the card is already closed by the time
        most lookups finish (FR-3.11).
        """

        self._selected_pos: PartOfSpeech | None = None
        self._lookup: LookupHandle | None = None
        self._chips: dict[PartOfSpeech, QPushButton] = {}
        self._mode = MeaningMode.AUTO
        self._mode_buttons: dict[MeaningMode, QPushButton] = {}
        self._entry_mode = EntryMode.SINGLE
        self._entry_mode_buttons: dict[EntryMode, QPushButton] = {}
        self._handed_off_lookup = False
        """True once a save (or duplicate hand-off) has taken ownership of the
        in-flight lookup, so ``closeEvent`` must NOT cancel it.

        Without this the card's own close -- which happens immediately on every
        successful save -- cancelled the very lookup ``save_word`` had just
        scheduled an enrichment patch for, so a word saved before its lookup
        resolved kept a blank meaning permanently (FR-2.9)."""

        self.setWindowFlags(Qt.WindowType.Popup | Qt.WindowType.FramelessWindowHint)
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True)

        self._build_ui()
        self._lookup_finished.connect(self._render_lookup_result)
        self._refresh_collections()
        self._update_save_enabled()

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    def _build_ui(self) -> None:
        outer = QVBoxLayout(self)
        outer.setContentsMargins(12, 12, 12, 12)

        card = QFrame()
        card.setObjectName("Card")
        shadow = QGraphicsDropShadowEffect(card)
        shadow.setBlurRadius(20)
        shadow.setOffset(0, 6)
        shadow.setColor(QColor(30, 41, 82, 40))
        card.setGraphicsEffect(shadow)
        outer.addWidget(card)

        body = QVBoxLayout(card)
        body.setContentsMargins(14, 12, 14, 14)
        body.setSpacing(8)

        body.addLayout(self._title_row())

        body.addWidget(self._field_label("WORD OR PHRASE"))
        body.addLayout(self._entry_mode_row())

        self._word_input = QLineEdit()
        self._word_input.setPlaceholderText("Type a word or phrase")
        self._word_input.textChanged.connect(self._on_word_changed)
        self._word_input.returnPressed.connect(self._on_save_clicked)
        body.addWidget(self._word_input)

        self._batch_hint = QLabel("")
        self._batch_hint.setObjectName("FieldHint")
        self._batch_hint.setWordWrap(True)
        self._batch_hint.hide()
        body.addWidget(self._batch_hint)

        body.addWidget(self._field_label("TYPE"))
        body.addLayout(self._chip_row())

        body.addWidget(self._field_label("COLLECTION"))
        self._collection_box = QComboBox()
        self._collection_box.currentIndexChanged.connect(self._on_collection_changed)
        body.addWidget(self._collection_box)

        self._inline_panel = self._inline_creation_panel()
        self._inline_panel.hide()
        body.addWidget(self._inline_panel)

        body.addWidget(self._field_label("MEANING"))
        body.addLayout(self._mode_toggle_row())

        self._result_panel = self._lookup_result_panel()
        self._result_panel.hide()
        body.addWidget(self._result_panel)

        self._manual_panel = self._manual_meaning_panel()
        self._manual_panel.hide()
        body.addWidget(self._manual_panel)

        self._save_button = QPushButton("Save word")
        self._save_button.setObjectName("Primary")
        self._save_button.setCursor(Qt.CursorShape.PointingHandCursor)
        self._save_button.clicked.connect(self._on_save_clicked)
        body.addWidget(self._save_button)

        self._status = QLabel("")
        self._status.setObjectName("StatusLine")
        self._status.setWordWrap(True)
        body.addWidget(self._status)

        self.setFixedWidth(CARD_WIDTH + 24)

    def _title_row(self) -> QHBoxLayout:
        row = QHBoxLayout()
        title = QLabel("Collect a word")
        title.setObjectName("CardTitle")
        row.addWidget(title)
        row.addStretch(1)

        close = QPushButton("\u2715")
        close.setObjectName("CloseX")
        close.setFixedSize(22, 22)
        close.setCursor(Qt.CursorShape.PointingHandCursor)
        close.clicked.connect(self.close)
        row.addWidget(close)
        return row

    @staticmethod
    def _field_label(text: str) -> QLabel:
        label = QLabel(text)
        label.setObjectName("FieldLabel")
        return label

    def _chip_row(self) -> QHBoxLayout:
        """Single-select part-of-speech chips (FR-2.2)."""
        row = QHBoxLayout()
        row.setSpacing(5)
        for pos in PartOfSpeech:
            chip = QPushButton(CHIP_LABELS[pos])
            chip.setObjectName("Chip")
            chip.setCheckable(True)
            # The full word, since the abbreviation is deliberately terse.
            chip.setToolTip(pos.value)
            chip.setCursor(Qt.CursorShape.PointingHandCursor)
            # Never let the layout squeeze a chip below the width its own text
            # needs -- that clipping is what made the full words unreadable.
            chip.setMinimumWidth(chip.sizeHint().width())
            chip.clicked.connect(lambda _checked=False, p=pos: self._select_pos(p))
            self._chips[pos] = chip
            row.addWidget(chip)
        row.addStretch(1)
        return row

    def _inline_creation_panel(self) -> QWidget:
        """The "+ New collection..." name field with Create and Cancel (FR-2.4)."""
        panel = QWidget()
        layout = QVBoxLayout(panel)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(6)

        self._new_collection_input = QLineEdit()
        self._new_collection_input.setPlaceholderText("Collection name")
        self._new_collection_input.returnPressed.connect(self._on_create_collection)
        layout.addWidget(self._new_collection_input)

        buttons = QHBoxLayout()
        buttons.setSpacing(6)

        create = QPushButton("Create")
        create.setObjectName("Primary")
        create.setCursor(Qt.CursorShape.PointingHandCursor)
        create.clicked.connect(self._on_create_collection)
        buttons.addWidget(create)

        cancel = QPushButton("Cancel")
        cancel.setObjectName("Ghost")
        cancel.setCursor(Qt.CursorShape.PointingHandCursor)
        cancel.clicked.connect(self._cancel_inline_creation)
        buttons.addWidget(cancel)

        layout.addLayout(buttons)
        return panel

    def _lookup_result_panel(self) -> QWidget:
        """Read-only Meaning and Example, shown before saving (FR-3.7)."""
        panel = QFrame()
        panel.setObjectName("InfoPanel")
        layout = QVBoxLayout(panel)
        layout.setContentsMargins(10, 8, 10, 8)
        layout.setSpacing(4)

        self._meaning_label = QLabel()
        self._meaning_label.setWordWrap(True)
        self._meaning_label.setTextFormat(Qt.TextFormat.RichText)
        layout.addWidget(self._meaning_label)

        self._example_label = QLabel()
        self._example_label.setWordWrap(True)
        self._example_label.setTextFormat(Qt.TextFormat.RichText)
        layout.addWidget(self._example_label)

        return panel

    def _entry_mode_row(self) -> QHBoxLayout:
        """One word vs. several, comma-separated (FR-2.12)."""
        row = QHBoxLayout()
        row.setSpacing(5)
        labels = {EntryMode.SINGLE: "One word", EntryMode.MULTIPLE: "Several"}
        for mode, text in labels.items():
            button = QPushButton(text)
            button.setObjectName("Chip")
            button.setCheckable(True)
            button.setChecked(mode is EntryMode.SINGLE)
            button.setCursor(Qt.CursorShape.PointingHandCursor)
            button.clicked.connect(
                lambda _checked=False, m=mode: self._select_entry_mode(m)
            )
            self._entry_mode_buttons[mode] = button
            row.addWidget(button)
        row.addStretch(1)
        return row

    def _select_entry_mode(self, mode: EntryMode) -> None:
        """Switch between single and multi-word entry (FR-2.12).

        Multi-word implies auto-lookup: a single typed meaning cannot be correct for
        several different words, so Manual is disabled rather than left available and
        quietly applying one definition to all of them.
        """
        if self._entry_mode is mode:
            return
        self._entry_mode = mode
        for candidate, button in self._entry_mode_buttons.items():
            button.setChecked(candidate is mode)

        if mode is EntryMode.MULTIPLE:
            if self._mode is MeaningMode.MANUAL:
                self._select_mode(MeaningMode.AUTO)
            self._word_input.setPlaceholderText("word one, word two, word three")
            self._save_button.setText("Save words")
            # Any lookup for the previous single word is now meaningless.
            self._cancel_current_lookup()
            self._result_panel.hide()
            self._set_status("")
        else:
            self._word_input.setPlaceholderText("Type a word or phrase")
            self._save_button.setText("Save word")
            self._batch_hint.hide()
            self._maybe_start_lookup()

        for button in self._mode_buttons.values():
            # Greyed rather than hidden, so the option is visibly unavailable instead
            # of appearing to not exist.
            button.setEnabled(mode is EntryMode.SINGLE)

        self._update_save_enabled()
        self._update_batch_hint()
        self.adjustSize()

    def _cancel_current_lookup(self) -> None:
        if self._lookup is not None:
            self._lookup.cancel()
            self._lookup = None
            self._handed_off_lookup = False

    def _update_batch_hint(self) -> None:
        """Show what the comma-separated text will actually become (FR-2.12).

        Echoing the parsed result matters because the parsing is lossy in ways the
        user cannot see otherwise: words are lowercased and repeats collapse. Showing
        the count and the first few words means a stray comma or an accidental
        duplicate is visible *before* saving.
        """
        if self._entry_mode is not EntryMode.MULTIPLE:
            self._batch_hint.hide()
            return

        words = parse_word_list(self._word_input.text())
        if not words:
            self._batch_hint.hide()
            return

        shown = ", ".join(words[:4])
        if len(words) > 4:
            shown += f", +{len(words) - 4} more"
        label = "word" if len(words) == 1 else "words"
        self._batch_hint.setText(f"{len(words)} {label}: {shown}")
        self._batch_hint.show()

    def _mode_toggle_row(self) -> QHBoxLayout:
        """Auto/Manual switch deciding where the meaning comes from (FR-2.11)."""
        row = QHBoxLayout()
        row.setSpacing(5)
        labels = {MeaningMode.AUTO: "Auto-lookup", MeaningMode.MANUAL: "Type it myself"}
        for mode, text in labels.items():
            button = QPushButton(text)
            button.setObjectName("Chip")
            button.setCheckable(True)
            button.setChecked(mode is MeaningMode.AUTO)
            button.setCursor(Qt.CursorShape.PointingHandCursor)
            button.clicked.connect(lambda _checked=False, m=mode: self._select_mode(m))
            self._mode_buttons[mode] = button
            row.addWidget(button)
        row.addStretch(1)
        return row

    def _manual_meaning_panel(self) -> QWidget:
        """Editable Meaning and Example, used in manual mode (FR-2.11)."""
        panel = QWidget()
        layout = QVBoxLayout(panel)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(6)

        layout.addWidget(self._field_label("YOUR MEANING"))
        self._manual_meaning_input = QLineEdit()
        self._manual_meaning_input.setPlaceholderText("What does it mean? (optional)")
        layout.addWidget(self._manual_meaning_input)

        layout.addWidget(self._field_label("YOUR EXAMPLE (OPTIONAL)"))
        self._manual_example_input = QLineEdit()
        self._manual_example_input.setPlaceholderText("An example sentence")
        layout.addWidget(self._manual_example_input)

        return panel

    def _select_mode(self, mode: MeaningMode) -> None:
        """Switch between auto-lookup and typed-in meaning (FR-2.11).

        Cancelling any in-flight lookup on the way into Manual is the point of
        this method: without it, a dictionary response that arrives after the
        switch could still patch the row with a definition the user explicitly
        chose not to use.
        """
        if self._mode is mode:
            return
        self._mode = mode
        for candidate, button in self._mode_buttons.items():
            button.setChecked(candidate is mode)

        if mode is MeaningMode.MANUAL:
            if self._lookup is not None:
                self._lookup.cancel()
                self._lookup = None
            self._result_panel.hide()
            self._manual_panel.show()
            self._set_status("")
            self._manual_meaning_input.setFocus()
        else:
            self._manual_panel.hide()
            # Re-running the lookup on the way back to Auto means the result
            # panel reflects the word currently typed rather than showing
            # stale state from before the switch.
            self._maybe_start_lookup()

        self.adjustSize()

    # ------------------------------------------------------------------
    # Input handling
    # ------------------------------------------------------------------

    def _select_pos(self, pos: PartOfSpeech) -> None:
        """Enforce single selection and restart lookup if the type changed."""
        self._selected_pos = pos
        for candidate, chip in self._chips.items():
            chip.setChecked(candidate is pos)
        self._update_save_enabled()
        self._maybe_start_lookup()

    def _on_word_changed(self, _text: str) -> None:
        self._update_save_enabled()
        self._update_batch_hint()

    def _update_save_enabled(self) -> None:
        """Save needs only a word and a type -- never a finished lookup (FR-2.7)."""
        if self._entry_mode is EntryMode.MULTIPLE:
            has_input = bool(parse_word_list(self._word_input.text()))
        else:
            has_input = bool(self._word_input.text().strip())
        self._save_button.setEnabled(has_input and self._selected_pos is not None)

    def _refresh_collections(self, select: str | None = None) -> None:
        """Rebuild the dropdown, keeping "+ New collection..." last (FR-2.3)."""
        self._collection_box.blockSignals(True)
        self._collection_box.clear()
        for name in self._service.available_collections():
            self._collection_box.addItem(name, name)
        self._collection_box.addItem(
            "+ New collection\u2026", NEW_COLLECTION_SENTINEL
        )

        if select is not None:
            index = self._collection_box.findData(select)
            if index >= 0:
                self._collection_box.setCurrentIndex(index)
        self._collection_box.blockSignals(False)

    def _on_collection_changed(self, _index: int) -> None:
        if self._collection_box.currentData() == NEW_COLLECTION_SENTINEL:
            self._begin_inline_creation()

    def _begin_inline_creation(self) -> None:
        """Swap the dropdown and Save for the inline name field (FR-2.4)."""
        self._collection_box.hide()
        self._save_button.hide()
        self._inline_panel.show()
        self._new_collection_input.clear()
        self._new_collection_input.setFocus()
        self._set_status("")
        self.adjustSize()

    def _cancel_inline_creation(self) -> None:
        """Restore the dropdown with the previous selection intact (FR-2.6)."""
        self._inline_panel.hide()
        self._collection_box.show()
        self._save_button.show()
        self._new_collection_input.clear()
        self._set_status("")

        if self._collection_box.currentData() == NEW_COLLECTION_SENTINEL:
            self._collection_box.blockSignals(True)
            self._collection_box.setCurrentIndex(0)
            self._collection_box.blockSignals(False)
        self.adjustSize()

    def _on_create_collection(self) -> None:
        """Validate and create, leaving the new collection selected (FR-2.5)."""
        try:
            created = self._service.create_collection_inline(
                self._new_collection_input.text()
            )
        except ValidationError as exc:
            self._set_status(str(exc), error=True)
            self._new_collection_input.setFocus()
            return

        self._inline_panel.hide()
        self._collection_box.show()
        self._save_button.show()
        self._refresh_collections(select=created.name)
        self._set_status("")
        self.adjustSize()

    # ------------------------------------------------------------------
    # Lookup
    # ------------------------------------------------------------------

    def _maybe_start_lookup(self) -> None:
        """Kick off a background lookup once a word and type are present (FR-3.1).

        A no-op in manual mode -- the user is supplying their own meaning, so
        querying the dictionaries would only risk a late result patching over
        it (FR-2.11).
        """
        if self._mode is MeaningMode.MANUAL:
            return

        # In multi-word mode there is no single word to preview, and starting a
        # lookup per keystroke across a growing list would fire dozens of requests
        # for words the user is still typing. The batch starts its lookups on save.
        if self._entry_mode is EntryMode.MULTIPLE:
            return

        word = self._word_input.text().strip()
        if not word or self._selected_pos is None:
            return

        if self._lookup is not None:
            # Superseded: the word or type changed, so this older lookup's result
            # would be for something the user is no longer collecting. Safe to
            # cancel because nothing has been saved against it yet.
            self._lookup.cancel()
            self._handed_off_lookup = False

        self._result_panel.hide()
        self._set_status(
            f'Looking up "{word}"\u2026 you can save now and the meaning will '
            "be filled in when it arrives."
        )

        handle = self._service.begin_lookup(word, self._selected_pos)
        self._lookup = handle
        # Marshal onto the UI thread: this callback fires on a worker.
        handle.subscribe(lambda result: self._lookup_finished.emit(result))

    def _render_lookup_result(self, result: object) -> None:
        """Show the resolved definition. Runs on the UI thread."""
        if not isinstance(result, LookupResult):  # pragma: no cover - signal guard
            return

        if result.is_empty:
            self._result_panel.hide()
            self._set_status(describe_source(LookupSource.NONE))
            self.adjustSize()
            return

        self._meaning_label.setText(
            f'<b>Meaning</b> \u2014 {result.meaning}'
        )
        if result.example:
            self._example_label.setText(f'<b>Example</b> \u2014 "{result.example}"')
            self._example_label.show()
        else:
            self._example_label.hide()

        self._result_panel.show()
        self._set_status(f"\u2713 {describe_source(result.source)}", success=True)
        self.adjustSize()

    def _set_status(
        self, text: str, *, success: bool = False, error: bool = False
    ) -> None:
        self._status.setText(text)
        if success:
            self._status.setObjectName("StatusLineSuccess")
        elif error:
            self._status.setObjectName("StatusLineError")
        else:
            self._status.setObjectName("StatusLine")
        # Re-apply the stylesheet so the object-name change takes effect.
        self._status.setStyleSheet(self._status.styleSheet())

    # ------------------------------------------------------------------
    # Saving
    # ------------------------------------------------------------------

    def _on_save_clicked(self) -> None:
        if not self._save_button.isEnabled():
            return

        word = self._word_input.text().strip()
        collection = self._collection_box.currentData()
        if collection == NEW_COLLECTION_SENTINEL or collection is None:
            self._set_status("Choose a collection for this word.", error=True)
            return

        assert self._selected_pos is not None

        if self._entry_mode is EntryMode.MULTIPLE:
            self._save_batch(str(collection))
            return

        is_manual = self._mode is MeaningMode.MANUAL
        manual_meaning = self._manual_meaning_input.text() if is_manual else None
        manual_example = self._manual_example_input.text() if is_manual else None

        try:
            outcome = self._service.save_word(
                word,
                self._selected_pos,
                str(collection),
                self._lookup,
                manual_meaning=manual_meaning,
                manual_example=manual_example,
            )
        except ValidationError as exc:
            self._set_status(str(exc), error=True)
            return

        if outcome.status is SaveStatus.SAVED:
            # The row exists now. In Auto mode with a lookup still running,
            # ``save_word`` has scheduled an enrichment patch against that row, so
            # the lookup must be allowed to finish in the background and fill in
            # the meaning after this card is gone (FR-2.9). Only a *discarded*
            # entry cancels its lookup -- see ``closeEvent``.
            if not is_manual and self._lookup is not None:
                self._handed_off_lookup = True
                # Hand the lookup to the Application so the character can report the
                # outcome after this card is gone (FR-3.11). A manual meaning needs no
                # announcement -- the user supplied it, so there is nothing to find.
                if self._on_lookup_reported is not None:
                    self._on_lookup_reported(word, self._lookup)
            self.close()
            return

        if outcome.status is SaveStatus.DUPLICATE_DETECTED:
            assert outcome.existing is not None
            incoming = self._service.build_entry(
                word,
                self._selected_pos,
                str(collection),
                self._lookup,
                manual_meaning=manual_meaning,
                manual_example=manual_example,
            )
            # The conflict popup now owns the decision, and Replace may use this
            # lookup's result, so this card must not cancel it on the way out.
            if not is_manual and self._lookup is not None:
                self._handed_off_lookup = True
            self.close()
            self._on_duplicate(outcome.existing, incoming)
            return

        # LOCKED: the workbook is open in Excel. The typed word is preserved on screen
        # so the user can close Excel and press Save again (FR-8.6).
        self._set_status(
            "The vocabulary file is open in Excel. Close it, then press Save word again.",
            error=True,
        )

    def _save_batch(self, collection: str) -> None:
        """Save every comma-separated word, each with its own lookup (FR-2.12).

        Unlike the single-word path this does **not** close the card on success: the
        result is a mixed report -- how many saved, which were already there -- and
        closing would throw that away before it could be read. The user closes it
        when they have seen the outcome.
        """
        assert self._selected_pos is not None

        words = parse_word_list(self._word_input.text())
        if not words:
            self._set_status("Enter at least one word.", error=True)
            return

        self._set_status(
            f"Saving {len(words)} words and looking each one up\u2026"
        )

        outcome = self._service.save_words(words, self._selected_pos, collection)

        # Every saved word announces its own outcome as it resolves, so a batch of
        # ten produces ten reports rather than one aggregate -- the user finds out
        # which words the dictionaries could not handle.
        if self._on_lookup_reported is not None:
            for saved_word, handle in outcome.handles:
                self._on_lookup_reported(saved_word, handle)

        self._render_batch_outcome(outcome)

    def _render_batch_outcome(self, outcome: BatchOutcome) -> None:
        """Report the mixed result of a batch, and clear what succeeded."""
        self._set_status(
            outcome.summary,
            success=bool(outcome.saved) and not outcome.locked,
            error=bool(outcome.locked),
        )

        if outcome.saved and not outcome.locked:
            # Clear the field so the card is ready for another batch, but leave it
            # populated when the workbook was locked -- the user needs the text to
            # retry with.
            self._word_input.clear()
            self._batch_hint.hide()

        self.adjustSize()

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def show_beside(self, anchor: tuple[int, int, int, int]) -> None:
        from PySide6.QtGui import QGuiApplication

        x, y, width, height = anchor
        screen = QGuiApplication.primaryScreen()
        if screen is not None:
            area = screen.availableGeometry()
            bounds = Rect(area.x(), area.y(), area.width(), area.height())
        else:  # pragma: no cover
            bounds = Rect(0, 0, 1920, 1080)

        self.adjustSize()
        placement = place_beside(
            Rect(x, y, width, height), self.width(), self.height(), bounds
        )
        self.move(placement.x, placement.y)
        self.show()
        self._word_input.setFocus()

    def keyPressEvent(self, event: QKeyEvent) -> None:
        """Escape discards the entry, matching the close affordance (E2-S1 branch 3a)."""
        if event.key() == Qt.Key.Key_Escape:
            self.close()
            return
        super().keyPressEvent(event)

    def closeEvent(self, event: object) -> None:
        """Abandon an in-flight lookup only if its entry was never saved.

        The distinction matters and was originally missing: this card closes
        immediately on every successful save, so cancelling unconditionally here
        also cancelled the enrichment patch ``save_word`` had just scheduled, and a
        word saved before its lookup resolved kept a blank meaning forever
        (FR-2.9). When the save (or the duplicate hand-off) has taken ownership of
        the lookup, it is left running so its result can still patch the row; only
        a genuinely discarded entry -- closed via the X or Escape without saving --
        cancels, so a late result cannot write a row the user abandoned.
        """
        if self._lookup is not None and not self._handed_off_lookup:
            self._lookup.cancel()
        self._lookup = None
        if self._on_closed is not None:
            self._on_closed()
        super().closeEvent(event)  # type: ignore[arg-type]
